version: '3'

services:
  webapp:
    # build: ./labelingwebserver
    # build from Dockerfile
    # context: ./labelingwebserver
    # dockerfile: Dockerfile
    image: labelwebserver:latest
    container_name: labelwebserver
    ports:
      - 9000:443
    restart: unless-stopped
    volumes:
      - /home/mushfiqrahman/dev/ProjectRoot:/home/mushfiqrahman/dev/ProjectRoot/

  labelapp:
    #image: rahman19/labelapp:latest
    image: labelingapp:latest
    container_name: labelingapp
    network_mode: host
    command: tail -f /dev/null
    volumes:
      - /home/mushfiqrahman/dev/ProjectRoot:/home/mushfiqrahman/dev/ProjectRoot/

  dbapp:
    image: labeldbapp:latest
    container_name: labeldbapp
    network_mode: host
    command: tail -f /dev/null
    volumes:
      - /home/mushfiqrahman/dev/backupdb:/usr/src/app/data/
  
