version: '3.7'

services:
  web:
    build: ./app
    entrypoint:
      - python3 main.py
    command: ""
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

volumes:
  postgres_data: